### ISSUE TITLE
DigitSelect appears to put items next to eachother instead of below eachother in the dropdown list. 

### ISSUE THREAD

**Issue by ViddeM** [cthit/react-digit-components#347] opened 2020-04-12 23:57 UTC

**Comment by Portals** [comment] 2020-04-13 12:32
Could you please provide a screenshot?

**Comment by ViddeM** [comment] 2020-04-13 13:58
![screenshot](https://user-images.githubusercontent.com/16452604/79126049-79812400-7d9f-11ea-9298-43b021313ac4.png)

This is the code:
`
<DigitSelect
                    upperLabel={"Meeting"}
                    outlined
                    valueToTextMap={{
                        option1: "Option1",
                        option2: "Option2",
                        option3: "Option3"
                    }}
                    onChange={e => {
                        props.onMeetingSelected(e.target.value);
                    }}
                    value={props.selectedMeetingID}
                    disabled={!props.meetings || Object.keys(props.meetings).length === 0}
                />
`

**Comment by Portals** [comment] 2020-04-13 14:05
Problem seems to be when you have a row as the parent.

**Comment by Portals** [comment] 2020-04-13 14:08
https://github.com/ViddeM/styrit-secretary-manager/blob/c39f1c8e948b8d2ef47f3ac9fd6fb8c873a56a46/frontend_new/src/use-cases/admin/screens/config/views/meeting/Meeting.view.jsx

**Comment by Portals** [comment] 2020-04-19 15:47
Closing since I can't reproduce this issue as a story

**Closed by Portals** 2020-04-19 15:47 UTC
Labels: Component: DigitSelect, Type: Bug, can't reproduce
